project:
  type: website

website:
  title: "Slava Akhmechet"
  description: "Slava Akhmechet's blog"
  site-url: https://spakhm.com
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/spakhm
      - icon: rss
        href: index.xml
  search: false
format:
  html:
    theme: cosmo
    css: styles.css



